apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage-v1
  namespace: exp
  labels:
    app: productpage
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage
      version: v1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9080"
        prometheus.io/path: "/metrics"
      labels:
        app: productpage
        version: v1
    spec:
      serviceAccountName: bookinfo-productpage
      hostPID: true
      hostIPC: true
      hostNetwork: true
      containers:
      - name: productpage
        image: sjlgaga/bookinfo-overhead:10k10k
        imagePullPolicy: Always
        ports:
        - containerPort: 9080
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}

